const stickers = [
  "/stickers/sticker1.png",
  "/stickers/sticker2.png",
  "/stickers/sticker3.png",
  "/stickers/sticker4.png",
  "/stickers/sticker5.png",
  "/stickers/sticker6.png",
  "/stickers/sticker7.png",
  "/stickers/sticker8.png",
  "/stickers/sticker9.png",
  "/stickers/sticker10.png",
  "/stickers/sticker11.png",
  "/stickers/01_SendingLove.webp",
  "/stickers/02_WellDoThisTogether.webp",
  "/stickers/03_Heart.webp",
  "/stickers/04_AirHighFive.webp",
  "/stickers/05_GroupVideoCalling.webp",
  "/stickers/06_StayConnected.webp",
  "/stickers/07_OK.webp",
  "/stickers/08_AreYouOK.webp",
  "/stickers/09_StayingHomeMug.webp",
  "/stickers/10_WorkingFromBed.webp",
  "/stickers/11_StayCalm.webp",
  "/stickers/12_Gymnastics.webp",
  "/stickers/13_DoubleChecking.webp",
  "/stickers/14_CatOnTheLaptop.webp",
  "/stickers/15_WorkingFromHomeF.webp",
  "/stickers/16_WorkingFromHomeM.webp",
  "/stickers/17_WashingHands.webp",
  "/stickers/18_DontTouchYourFace.webp",
  "/stickers/19_SocialDistancing.webp",
  "/stickers/20_SuperheroNurse.webp",
  "/stickers/21_YouAreMyHero.webp",
];

export default stickers;
